name: Rector

on:
  pull_request: null

jobs:
  rector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: ramsey/composer-install@v2

      - name: Rector - Fix
        run: vendor/bin/rector process --ansi

      - name: Easy Coding Standard - Fix
        run: vendor/bin/ecs check --fix --ansi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PR_PAT }}
