name: Rector

on:
  push: null
  pull_request: null

jobs:
  rector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - uses: ramsey/composer-install@v2
      - run: vendor/bin/rector process --ansi --dry-run
      - run: vendor/bin/ecs check --ansi
